import { Classroom, AttendanceRecord, SystemNotification } from '../types';

export interface MajorGroup {
  groupName: string;
  majors: string[];
}

export const CTU_PEDAGOGY_MAJORS: string[] = [
  'Sư phạm Toán học',
  'Sư phạm Tin học',
  'Sư phạm Vật lý',
  'Sư phạm Hóa học',
  'Sư phạm Sinh học',
  'Sư phạm Ngữ văn',
  'Sư phạm Lịch sử',
  'Sư phạm Địa lý',
  'Sư phạm Tiếng Anh',
  'Sư phạm Tiếng Pháp',
  'Giáo dục Tiểu học',
  'Giáo dục Mầm non',
  'Giáo dục Thể chất',
  'Sư phạm Khoa học tự nhiên',
  'Sư phạm Lịch sử - Địa lý',
];

export const MAJOR_GROUPS: MajorGroup[] = [
  {
    groupName: 'Trường Sư phạm - Đại học Cần Thơ',
    majors: CTU_PEDAGOGY_MAJORS,
  },
  {
    groupName: 'Trường Công nghệ Thông tin & Truyền thông - ĐHCT',
    majors: [
      'Công nghệ thông tin',
      'Kỹ thuật phần mềm',
      'Hệ thống thông tin',
      'Khoa học máy tính',
      'An toàn thông tin',
      'Kỹ thuật mạng & Truyền thông dữ liệu',
      'Trí tuệ nhân tạo & Khoa học dữ liệu',
    ],
  },
  {
    groupName: 'Trường Kinh tế & Các khối ngành khác - ĐHCT',
    majors: [
      'Quản trị kinh doanh',
      'Kinh tế số & Thương mại điện tử',
      'Tài chính - Ngân hàng',
      'Kế toán - Kiểm toán',
      'Ngôn ngữ Anh',
      'Logistics & Quản lý chuỗi cung ứng',
      'Marketing số',
      'Kỹ thuật điều khiển & Tự động hóa',
      'Kỹ thuật cơ điện tử',
      'Kỹ thuật điện - điện tử',
      'Khoa học môi trường',
      'Luật kinh tế',
      'Y đa khoa & Dược học',
      'Nông nghiệp công nghệ cao',
      'Thú y',
      'Nuôi trồng thủy sản',
    ],
  },
];

// Flat list containing all majors with Pedagogy included
export const POPULAR_MAJORS: string[] = MAJOR_GROUPS.flatMap((g) => g.majors);

export const DEFAULT_CLASSROOMS: Classroom[] = [
  {
    id: 'class-1',
    code: 'CNTT2024-K48',
    name: 'Phát triển Ứng dụng Web & Di động',
    room: 'Giảng đường A1 - Phòng 302',
    lecturerName: 'ThS. Trần Hoàng Nam',
    lecturerEmail: 'nam.th@ctu.edu.vn',
    requireGps: true,
    classroomLocation: {
      latitude: 10.030998,
      longitude: 105.768994,
      radiusMeters: 200,
      addressName: 'Khu II, Đại học Cần Thơ, Đường 3/2, Xuân Khánh, Ninh Kiều, Cần Thơ',
    },
    students: [
      {
        id: 'stu-1',
        studentId: 'B2408109',
        fullName: 'Nguyễn Văn Sang',
        major: 'Công nghệ thông tin',
        email: 'sangb2408109@student.ctu.edu.vn',
        joinedAt: '2026-09-01',
      },
      {
        id: 'stu-2',
        studentId: 'B2305412',
        fullName: 'Lê Thị Mỹ Duyên',
        major: 'Kỹ thuật phần mềm',
        email: 'duyenb2305412@student.ctu.edu.vn',
        joinedAt: '2026-09-01',
      },
      {
        id: 'stu-3',
        studentId: 'B2209315',
        fullName: 'Trần Bảo Long',
        major: 'Hệ thống thông tin',
        email: 'longb2209315@student.ctu.edu.vn',
        joinedAt: '2026-09-01',
      },
      {
        id: 'stu-4',
        studentId: 'B2401128',
        fullName: 'Võ Hoàng Quân',
        major: 'Khoa học máy tính',
        email: 'quanb2401128@student.ctu.edu.vn',
        joinedAt: '2026-09-01',
      },
      {
        id: 'stu-5',
        studentId: 'B2307891',
        fullName: 'Đặng Ngọc Thảo Vy',
        major: 'Kinh tế số & Thương mại điện tử',
        email: 'vyb2307891@student.ctu.edu.vn',
        joinedAt: '2026-09-01',
      },
      {
        id: 'stu-6',
        studentId: 'B2403321',
        fullName: 'Phạm Minh Khang',
        major: 'Công nghệ thông tin',
        email: 'khangb2403321@student.ctu.edu.vn',
        joinedAt: '2026-09-01',
      }
    ],
    createdAt: Date.now() - 86400000 * 14,
  },
  {
    id: 'class-2',
    code: 'CS102-K49',
    name: 'Cấu trúc Dữ liệu & Giải thuật',
    room: 'Phòng thực hành Máy tính C1',
    lecturerName: 'TS. Lê Thanh Sơn',
    lecturerEmail: 'son.lt@ctu.edu.vn',
    requireGps: true,
    classroomLocation: {
      latitude: 10.7725,
      longitude: 106.6578,
      radiusMeters: 150,
      addressName: 'Cơ sở Lý Thường Kiệt, Quận 10, TP. Hồ Chí Minh',
    },
    students: [
      {
        id: 'stu-201',
        studentId: 'B2408109',
        fullName: 'Nguyễn Văn Sang',
        major: 'Công nghệ thông tin',
        email: 'sangb2408109@student.ctu.edu.vn',
        joinedAt: '2026-09-05',
      },
      {
        id: 'stu-202',
        studentId: 'B2406712',
        fullName: 'Huỳnh Gia Huy',
        major: 'Khoa học máy tính',
        email: 'huyb2406712@student.ctu.edu.vn',
        joinedAt: '2026-09-05',
      },
      {
        id: 'stu-203',
        studentId: 'B2409941',
        fullName: 'Ngô Phương Thảo',
        major: 'Trí tuệ nhân tạo & Khoa học dữ liệu',
        email: 'thaob2409941@student.ctu.edu.vn',
        joinedAt: '2026-09-05',
      }
    ],
    createdAt: Date.now() - 86400000 * 7,
  },
  {
    id: 'class-3',
    code: 'SE301-K47',
    name: 'Kiến trúc & Thiết kế Phần mềm',
    room: 'Hội trường B - Tòa nhà Công nghệ',
    lecturerName: 'PGS. TS. Phạm Minh Trí',
    lecturerEmail: 'tri.pm@ctu.edu.vn',
    requireGps: false,
    students: [
      {
        id: 'stu-301',
        studentId: 'B2209315',
        fullName: 'Trần Bảo Long',
        major: 'Hệ thống thông tin',
        email: 'longb2209315@student.ctu.edu.vn',
        joinedAt: '2026-09-10',
      },
      {
        id: 'stu-302',
        studentId: 'B2305412',
        fullName: 'Lê Thị Mỹ Duyên',
        major: 'Kỹ thuật phần mềm',
        email: 'duyenb2305412@student.ctu.edu.vn',
        joinedAt: '2026-09-10',
      }
    ],
    createdAt: Date.now() - 86400000 * 3,
  },
  {
    id: 'class-4',
    code: 'SPTOAN-K49',
    name: 'Phương pháp Dạy học Toán học & Ứng dụng CNTT',
    room: 'Giảng đường B1 - Trường Sư phạm (Khu II ĐHCT)',
    lecturerName: 'TS. Nguyễn Thị Mai Hương',
    lecturerEmail: 'huong.ntm@ctu.edu.vn',
    requireGps: true,
    classroomLocation: {
      latitude: 10.031500,
      longitude: 105.768500,
      radiusMeters: 180,
      addressName: 'Trường Sư phạm, Khu II, Đại học Cần Thơ, Đường 3/2, Ninh Kiều, Cần Thơ',
    },
    students: [
      {
        id: 'stu-401',
        studentId: 'B2301234',
        fullName: 'Nguyễn Thanh Thảo',
        major: 'Sư phạm Toán học',
        email: 'thaob2301234@student.ctu.edu.vn',
        joinedAt: '2026-09-02',
      },
      {
        id: 'stu-402',
        studentId: 'B2302345',
        fullName: 'Trần Minh Trí',
        major: 'Sư phạm Tin học',
        email: 'trib2302345@student.ctu.edu.vn',
        joinedAt: '2026-09-02',
      },
      {
        id: 'stu-403',
        studentId: 'B2303456',
        fullName: 'Huỳnh Thị Cẩm Tiên',
        major: 'Giáo dục Tiểu học',
        email: 'tienb2303456@student.ctu.edu.vn',
        joinedAt: '2026-09-02',
      },
      {
        id: 'stu-404',
        studentId: 'B2404567',
        fullName: 'Lê Hoàng Phúc',
        major: 'Sư phạm Tiếng Anh',
        email: 'phucb2404567@student.ctu.edu.vn',
        joinedAt: '2026-09-02',
      },
      {
        id: 'stu-405',
        studentId: 'B2408109',
        fullName: 'Nguyễn Văn Sang',
        major: 'Sư phạm Tin học',
        email: 'sangb2408109@student.ctu.edu.vn',
        joinedAt: '2026-09-02',
      }
    ],
    createdAt: Date.now() - 86400000 * 2,
  }
];

// Compatibility
export const DEFAULT_SESSIONS = DEFAULT_CLASSROOMS;

const todayStr = new Date().toISOString().slice(0, 10);
const yesterday = new Date(Date.now() - 86400000).toISOString().slice(0, 10);

export const INITIAL_ATTENDANCE_RECORDS: AttendanceRecord[] = [
  {
    id: 'att-1',
    studentId: 'B2408109',
    fullName: 'Nguyễn Văn Sang',
    major: 'Công nghệ thông tin',
    studentEmail: 'sangb2408109@student.ctu.edu.vn',
    sessionCode: 'CNTT2024-K48',
    courseName: 'Phát triển Ứng dụng Web & Di động',
    dateOnly: todayStr,
    timeOnly: '14:30:15',
    timestamp: '14:30:15 - Hôm nay',
    createdAt: Date.now() - 15 * 60000,
    location: {
      latitude: 10.030950,
      longitude: 105.769020,
      accuracy: 12,
      address: 'Khu II, Đại học Cần Thơ, Đường 3/2, Ninh Kiều, Cần Thơ',
      timestamp: Date.now() - 15 * 60000,
    },
    locationStatus: 'valid',
    distanceToClassroom: 15,
    qrCodeUsed: 'QR-CNTT2024-K48-SECURE-A1302',
    qrVerified: true,
  },
  {
    id: 'att-2',
    studentId: 'B2305412',
    fullName: 'Lê Thị Mỹ Duyên',
    major: 'Kỹ thuật phần mềm',
    studentEmail: 'duyenb2305412@student.ctu.edu.vn',
    sessionCode: 'CNTT2024-K48',
    courseName: 'Phát triển Ứng dụng Web & Di động',
    dateOnly: todayStr,
    timeOnly: '14:32:40',
    timestamp: '14:32:40 - Hôm nay',
    createdAt: Date.now() - 12 * 60000,
    location: {
      latitude: 10.031080,
      longitude: 105.768910,
      accuracy: 18,
      address: 'Nhà học C1, Đại học Cần Thơ, Ninh Kiều, Cần Thơ',
      timestamp: Date.now() - 12 * 60000,
    },
    locationStatus: 'valid',
    distanceToClassroom: 32,
    qrCodeUsed: 'QR-CNTT2024-K48-SECURE-A1302',
    qrVerified: true,
  },
  {
    id: 'att-3',
    studentId: 'B2209315',
    fullName: 'Trần Bảo Long',
    major: 'Hệ thống thông tin',
    studentEmail: 'longb2209315@student.ctu.edu.vn',
    sessionCode: 'CNTT2024-K48',
    courseName: 'Phát triển Ứng dụng Web & Di động',
    dateOnly: todayStr,
    timeOnly: '14:35:02',
    timestamp: '14:35:02 - Hôm nay',
    createdAt: Date.now() - 9 * 60000,
    location: {
      latitude: 10.034500,
      longitude: 105.772100,
      accuracy: 35,
      address: 'Đường 30 Tháng 4, Hưng Lợi, Ninh Kiều, Cần Thơ',
      timestamp: Date.now() - 9 * 60000,
    },
    locationStatus: 'out_of_range',
    distanceToClassroom: 520,
    qrCodeUsed: 'QR-CNTT2024-K48-SECURE-A1302',
    qrVerified: true,
  },
  {
    id: 'att-4',
    studentId: 'B2401128',
    fullName: 'Võ Hoàng Quân',
    major: 'Khoa học máy tính',
    studentEmail: 'quanb2401128@student.ctu.edu.vn',
    sessionCode: 'CNTT2024-K48',
    courseName: 'Phát triển Ứng dụng Web & Di động',
    dateOnly: todayStr,
    timeOnly: '14:38:19',
    timestamp: '14:38:19 - Hôm nay',
    createdAt: Date.now() - 6 * 60000,
    location: {
      latitude: 10.030890,
      longitude: 105.768950,
      accuracy: 8,
      address: 'Khu II, Đại học Cần Thơ, Đường 3/2, Ninh Kiều, Cần Thơ',
      timestamp: Date.now() - 6 * 60000,
    },
    locationStatus: 'valid',
    distanceToClassroom: 18,
    qrCodeUsed: 'QR-CNTT2024-K48-SECURE-A1302',
    qrVerified: true,
  },
  {
    id: 'att-5',
    studentId: 'B2307891',
    fullName: 'Đặng Ngọc Thảo Vy',
    major: 'Kinh tế số & Thương mại điện tử',
    studentEmail: 'vyb2307891@student.ctu.edu.vn',
    sessionCode: 'CNTT2024-K48',
    courseName: 'Phát triển Ứng dụng Web & Di động',
    dateOnly: todayStr,
    timeOnly: '14:41:05',
    timestamp: '14:41:05 - Hôm nay',
    createdAt: Date.now() - 3 * 60000,
    locationStatus: 'no_gps',
    qrCodeUsed: 'QR-CNTT2024-K48-SECURE-A1302',
    qrVerified: true,
  },
  {
    id: 'att-6',
    studentId: 'B2408109',
    fullName: 'Nguyễn Văn Sang',
    major: 'Công nghệ thông tin',
    studentEmail: 'sangb2408109@student.ctu.edu.vn',
    sessionCode: 'CS102-K49',
    courseName: 'Cấu trúc Dữ liệu & Giải thuật',
    dateOnly: yesterday,
    timeOnly: '08:15:20',
    timestamp: '08:15:20 - Hôm qua',
    createdAt: Date.now() - 86400000 + 15 * 60000,
    location: {
      latitude: 10.7724,
      longitude: 106.6579,
      accuracy: 14,
      address: 'Phòng C1, Lý Thường Kiệt, Q.10, TP.HCM',
      timestamp: Date.now() - 86400000 + 15 * 60000,
    },
    locationStatus: 'valid',
    distanceToClassroom: 22,
    qrCodeUsed: 'QR-CS102-K49-PHT-C1',
    qrVerified: true,
  },
  {
    id: 'att-7',
    studentId: 'B2301234',
    fullName: 'Nguyễn Thanh Thảo',
    major: 'Sư phạm Toán học',
    studentEmail: 'thaob2301234@student.ctu.edu.vn',
    sessionCode: 'SPTOAN-K49',
    courseName: 'Phương pháp Dạy học Toán học & Ứng dụng CNTT',
    dateOnly: todayStr,
    timeOnly: '07:45:10',
    timestamp: '07:45:10 - Hôm nay',
    createdAt: Date.now() - 45 * 60000,
    location: {
      latitude: 10.031510,
      longitude: 105.768520,
      accuracy: 10,
      address: 'Trường Sư phạm, Khu II ĐHCT, Ninh Kiều, Cần Thơ',
      timestamp: Date.now() - 45 * 60000,
    },
    locationStatus: 'valid',
    distanceToClassroom: 12,
    qrCodeUsed: 'QR-SPTOAN-K49-B1-LIVE',
    qrVerified: true,
  },
  {
    id: 'att-8',
    studentId: 'B2302345',
    fullName: 'Trần Minh Trí',
    major: 'Sư phạm Tin học',
    studentEmail: 'trib2302345@student.ctu.edu.vn',
    sessionCode: 'SPTOAN-K49',
    courseName: 'Phương pháp Dạy học Toán học & Ứng dụng CNTT',
    dateOnly: todayStr,
    timeOnly: '07:48:32',
    timestamp: '07:48:32 - Hôm nay',
    createdAt: Date.now() - 42 * 60000,
    location: {
      latitude: 10.031480,
      longitude: 105.768490,
      accuracy: 15,
      address: 'Khu giảng đường B1, Trường Sư phạm, ĐH Cần Thơ',
      timestamp: Date.now() - 42 * 60000,
    },
    locationStatus: 'valid',
    distanceToClassroom: 16,
    qrCodeUsed: 'QR-SPTOAN-K49-B1-LIVE',
    qrVerified: true,
  }
];

export const INITIAL_NOTIFICATIONS: SystemNotification[] = [
  {
    id: 'notif-1',
    type: 'student_email',
    targetRole: 'student',
    recipientEmail: 'sangb2408109@student.ctu.edu.vn',
    recipientName: 'Nguyễn Văn Sang (B2408109)',
    title: 'Xác nhận điểm danh thành công',
    content: 'Bạn đã điểm danh thành công môn Phát triển Ứng dụng Web & Di động (CNTT2024-K48) vào lúc 14:30:15 với vị trí GPS hợp lệ.',
    classCode: 'CNTT2024-K48',
    className: 'Phát triển Ứng dụng Web & Di động',
    studentId: 'B2408109',
    studentName: 'Nguyễn Văn Sang',
    timestamp: '14:30:16 - Hôm nay',
    createdAt: Date.now() - 15 * 60000,
    isRead: false,
    emailPayload: {
      subject: '[ĐHCT] Xác nhận điểm danh môn Phát triển Ứng dụng Web & Di động',
      studentName: 'Nguyễn Văn Sang',
      studentId: 'B2408109',
      courseName: 'Phát triển Ứng dụng Web & Di động',
      sessionCode: 'CNTT2024-K48',
      timestamp: '14:30:15 - Hôm nay',
      locationText: 'Khu II, Đại học Cần Thơ, Đường 3/2, Ninh Kiều, Cần Thơ (10.03095, 105.76902)',
      gpsStatusText: 'Hợp lệ trong phòng học (Cách tâm 15m)',
      qrToken: 'QR-CNTT2024-K48-SECURE-A1302',
    }
  },
  {
    id: 'notif-2',
    type: 'teacher_alert',
    targetRole: 'teacher',
    recipientEmail: 'nam.th@ctu.edu.vn',
    recipientName: 'ThS. Trần Hoàng Nam',
    title: 'Sinh viên mới điểm danh: Nguyễn Văn Sang',
    content: 'Sinh viên Nguyễn Văn Sang (MSSV: B2408109) đã điểm danh lớp CNTT2024-K48 lúc 14:30:15. GPS: Hợp lệ (~15m).',
    classCode: 'CNTT2024-K48',
    className: 'Phát triển Ứng dụng Web & Di động',
    studentId: 'B2408109',
    studentName: 'Nguyễn Văn Sang',
    timestamp: '14:30:16 - Hôm nay',
    createdAt: Date.now() - 15 * 60000,
    isRead: false,
  },
  {
    id: 'notif-3',
    type: 'teacher_warning',
    targetRole: 'teacher',
    recipientEmail: 'nam.th@ctu.edu.vn',
    recipientName: 'ThS. Trần Hoàng Nam',
    title: 'Cảnh báo: Sinh viên điểm danh ngoài bán kính GPS',
    content: 'Sinh viên Trần Bảo Long (MSSV: B2209315) điểm danh cách phòng học 520 mét (vượt giới hạn 200m).',
    classCode: 'CNTT2024-K48',
    className: 'Phát triển Ứng dụng Web & Di động',
    studentId: 'B2209315',
    studentName: 'Trần Bảo Long',
    timestamp: '14:35:03 - Hôm nay',
    createdAt: Date.now() - 9 * 60000,
    isRead: false,
  }
];
